# Generated by Django 5.2.4 on 2025-08-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'Can view books'), ('can_add', 'Can add books'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete books'))},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_picture',
            new_name='profile_photo',
        ),
    ]
