# Generated by Django 5.2.4 on 2025-08-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'Can view books'), ('can_create', 'Can add books'), ('can_edit', 'Can edit books'), ('can_delete', 'Can delete books'))},
        ),
    ]
