# Generated by Django 5.2.4 on 2025-08-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_profile_wastesale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastepost',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='wastesale',
            name='waste_post',
        ),
        migrations.RemoveField(
            model_name='wastesale',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='wastesale',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='WastePost',
        ),
        migrations.DeleteModel(
            name='WasteSale',
        ),
    ]
