# Generated by Django 5.2.4 on 2025-08-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_wastepost_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastepost',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
