# Generated by Django 5.2.4 on 2025-08-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add a book'), ('can_delete_book', 'Can delete a book'), ('can_view_book', 'Can view books'), ('can_change_book', 'Can change a book'))},
        ),
    ]
