# Generated by Django 5.2.4 on 2025-07-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a book'), ('can_delete_book', 'Can delete a book'), ('can_view_book', 'Can view books'), ('can_update_book', 'Can update a book')]},
        ),
    ]
